### ISSUE TITLE
テンプレートスタイルの設定

### ISSUE THREAD

**Issue by luckylat** [luckylat/cp-template#3]
Codeforcesのようにクエリ問題ばっか来るようなときに使えるオプション

**Comment by luckylat** [comment]
```
cp-template --folder ABCxxx --number 6 --style query
cp-template -F ABCxxx -N 6 -S query
```
みたいな形にする?

```toml
[templates]
    default = "default template path"
    query = "query template path"
```
みたいなconfigファイルを用意するとか
